robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_left
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAO9WCV-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [8, 9, 10, 11, 12, 13]
    joint_offsets: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    joint_signs: [1.0, -1.0, 1.0, -1.0, 1.0, 1.0]
    gripper_config: [14, 48.869140625, 108.369140625]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
hz: 30
max_steps: 1000
