robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_left
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAO9WPU-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [7, 55.869140625, 108.369140625]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
hz: 30
max_steps: 1000

# Data collection configuration
collection:
  max_episode_length: 10000
  act_noise_std: 0.001
  no_ops_threshold: 0.004
  no_ops_last_detected_time: 3
  lock_rotation_detected_time: 1

# Data storage configuration
storage:
  episodes: 50
  base_dir: "/home/sean/Desktop/YAM/gello_software/data"
  task_directory: "fold the cloth"
  language_instruction: "fold the cloth"
  teleop_device: "oculus" # ["oculus", "keyboard", "gello", "none"]
  save_format: "json" # ["json", "npy"]
  old_format: false

# Policy configuration
policy:
  # _target_: lerobot.common.policies.pi05.configuration_pi05.PI05Config
  repo_id: "Jiafei1224/d"
  checkpoint_path: "Jiafei1224/a"
